language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk14

assemble: true
install: true
script:
  - ./gradlew build mapNamedJar javadocJar checkMappings --stacktrace -i

notifications:
  email: false